  # Publish all joint states -----------------------------------
   joint_state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50  
  
  # Position Controllers ---------------------------------------
   joint2_position_controller:
     type: effort_controllers/JointPositionController
     joint: joint2
     pid: {p: 10.0, i: 0.1, d: 0.4}
   joint3_position_controller:
     type: effort_controllers/JointPositionController
     joint: joint3
     pid: {p: 10.0, i: 0.1, d: 0.4}
   joint4_position_controller:
     type: effort_controllers/JointPositionController
     joint: joint4
     pid: {p: 10.0, i: 0.1, d: 0.4}
   joint5_position_controller:
     type: effort_controllers/JointPositionController
     joint: joint5
     pid: {p: 10.0, i: 0.1, d: 0.4}
   joint6_position_controller:
     type: effort_controllers/JointPositionController
     joint: joint6
     pid: {p: 10.0, i: 0.1, d: 0.4}
   joint7_position_controller:
     type: effort_controllers/JointPositionController
     joint: joint7
     pid: {p: 10.0, i: 0.1, d: 0.4}
   joint8_position_controller:
     type: effort_controllers/JointPositionController
     joint: joint_finger_right
     pid: {p: 10.0, i: 0.1, d: 0.4}
   joint9_position_controller:
     type: effort_controllers/JointPositionController
     joint: joint_finger_left
     pid: {p: 10.0, i: 0.1, d: 0.4}

#debug----------------------------
  # joint2_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint2
  #   pid: {p: 5.0, i: 0.01, d: 0.1}
  # joint3_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint3
  #   pid: {p: 5.0, i: 0.01, d: 0.1}
  # joint4_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint4
  #   pid: {p: 5.0, i: 0.01, d: 0.1}