tilt_controller_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 2.0
    motor:
        id: 1
        init: 512
        min: 0
        max: 4095

tilt_controller_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 2.0
    motor:
        id: 2
        init: 512
        min: 0
        max: 4095

